# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50d904dabff9cbffb74506582f4d2ba8ef2d2cdecbc8e9c1e88640f089bdbf8d69b1c06c4eed9e18ca0b4acaa763bd390fd85fe2e3190f3bc3f70d9e0bd468c9

test:
  secret_key_base: 5343c016fa2d6e0c5f7d182d506957d7bd660f843b5c1afe9a2f013c2df1b1ccae590ed31cd32fd4442e8eef0513da854fe38a674cc511dc995a152a39bfeb50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
